'use strict';
// Auto-generated by port-server-modules.js -- DO NOT EDIT DIRECTLY.
// Source of truth is webapp/server/{ingest/constants,ingest/normalize,ingest/validate,stats,analysis,search}.js
// Re-run `node port-server-modules.js` after editing any of those.

/* ============ ported from ../webapp/server/ingest/constants.js ============ */
// Canonical column names expected in the source workbook/CSV (order-independent,
// matched case-insensitively with whitespace trimmed). Trailing unnamed/blank
// columns in the source file are ignored automatically by parseWorkbook.js.
const REQUIRED_COLUMNS = [
  'S. No.',
  'Enzyme',
  'Acceptor class',
  'Family',
  'Origin',
  'Gene from organism',
  'Prenyl acceptor (Aromatic substrate) - Accepted',
  'Prenyl acceptor (Aromatic substrate) - Medium to Not Accepted',
  'Prenyl donor - Accepted',
  'Prenyl donor - Medium to Not Accepted',
  'Metal ion - Accepted',
  'Metal ion - Medium to Not Accepted',
  'Expression in',
  'Product',
  'Regio specificity',
  'Km value',
  'Optimal pH',
  'Optimal temperature',
  'Year',
  'Author',
  'doi',
];

// Fixed vocabulary of prenyl-donor codes. Used to decide whether a comma inside
// a donor cell separates distinct substrates (as opposed to being punctuation
// inside a free-text note, e.g. "GPP, this enzyme has a broad specificity").
const DONOR_TOKENS = [
  'DMAPP', 'GPP', 'FPP', 'GGPP', 'IPP', 'LPP', 'NPP', 'PPP', 'SPP', 'PDP',
  'OCTAPRENYL DIPHOSPHATE', 'DECAPRENYL DIPHOSPHATE',
];

const DONOR_TOKEN_REGEX = new RegExp(
  '^(' + DONOR_TOKENS.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')$',
  'i'
);

// Metal ion / cofactor token shape, e.g. Mg2+, Fe3+, K+, Al3+.
const METAL_TOKEN_REGEX = /^[A-Za-z]{1,2}\d?\+{1,3}$/;

const PROMISCUOUS_NOTE_REGEX = /broad specificity|promiscuous/i;

const PH_MIN = 0;
const PH_MAX = 14;
const TEMP_MIN = 0;
const TEMP_MAX = 100;

const KM_UNIT_TO_UM = {
  nm: 0.001,
  'nM': 0.001,
  um: 1,
  'µm': 1,
  'μm': 1,
  mm: 1000,
  m: 1000000,
};

/* ============ ported from ../webapp/server/ingest/normalize.js ============ */
// Standalone-number matcher: rejects digits glued to letters on either side,
// so "1367TH-4PX" and "v1" never yield spurious numeric values, while
// "8" in "8 for formation of 1367TH-4PX with v1" is still captured.
const STANDALONE_NUMBER = /(?<![A-Za-z0-9])(\d+(?:[.,]\d+)?)(?![A-Za-z0-9])/g;

function toNumber(token) {
  // A bare "8,8" pattern is a European decimal (8.8); anything else keeps '.'.
  if (/^\d+,\d+$/.test(token)) return parseFloat(token.replace(',', '.'));
  return parseFloat(token.replace(',', ''));
}

function standaloneNumbers(text) {
  if (!text) return [];
  const out = [];
  let m;
  STANDALONE_NUMBER.lastIndex = 0;
  while ((m = STANDALONE_NUMBER.exec(text)) !== null) out.push(toNumber(m[1]));
  return out;
}

// ---------------------------------------------------------------------------
// Acceptor-class normalization (capitalization + whitespace only)
// ---------------------------------------------------------------------------
function normalizeAcceptorClass(raw, auditLog) {
  if (!raw) return { value: null, wasNormalized: false };
  const trimmed = String(raw).replace(/\s+/g, ' ').trim();
  const canonical = trimmed.replace(/\w\S*/g, (w) => w[0].toUpperCase() + w.slice(1).toLowerCase());
  if (canonical !== trimmed) {
    auditLog.push({
      field: 'Acceptor class',
      raw: raw,
      normalized: canonical,
      rule: 'capitalization/whitespace fold',
    });
  }
  return { value: canonical, wasNormalized: canonical !== raw };
}

// ---------------------------------------------------------------------------
// Genus / species extraction
// ---------------------------------------------------------------------------
function splitOrganism(raw) {
  if (!raw) return { genus: null, species: null, commonName: null, organism: null };
  const text = String(raw).trim();
  const parenMatch = text.match(/^(.*?)\s*\(([^)]+)\)\s*$/);
  const namePart = parenMatch ? parenMatch[1].trim() : text;
  const commonName = parenMatch ? parenMatch[2].trim() : null;
  const tokens = namePart.split(/\s+/).filter(Boolean);
  const genus = tokens[0] || null;
  let species = null;
  if (tokens[1] && /^[a-z]/.test(tokens[1]) && tokens[1] !== 'sp.' && tokens[1] !== 'sp') {
    species = tokens[1].replace(/[.,]$/, '');
  }
  return { genus, species, commonName, organism: namePart };
}

// ---------------------------------------------------------------------------
// Controlled-vocabulary list explosion (donors / metal ions)
// ---------------------------------------------------------------------------
function canonicalizeToken(line, tokenRegex) {
  if (tokenRegex === METAL_TOKEN_REGEX) {
    return line.replace(/^([A-Za-z]{1,2})(\d*\+{1,3})$/, (m, el, charge) => el[0].toUpperCase() + el.slice(1).toLowerCase() + charge);
  }
  return line.toUpperCase().replace(/^OCTAPRENYL DIPHOSPHATE$/i, 'Octaprenyl diphosphate');
}

function explodeControlledList(raw, tokenRegex, fieldName, sourceRow, auditLog) {
  if (!raw) return { tokens: [], notes: [] };
  const text = String(raw);
  const lines = text.split('\n').flatMap((l) => l.split(','));
  const tokens = [];
  const notes = [];

  lines.forEach((lineRaw) => {
    let line = lineRaw.trim();
    if (!line) return;
    const original = line;
    line = line.replace(/^\d+[.)]\s*/, ''); // strip leading list numbering
    let concentration = null;
    const concMatch = line.match(/^(\d+(?:\.\d+)?)\s*(m|µ|u|n)?M\s+(.*)$/i);
    if (concMatch) {
      concentration = `${concMatch[1]} ${concMatch[2] || ''}M`.trim();
      line = concMatch[3].trim();
    }
    const percentMatch = line.match(/^(.*?)\s*\((\d+(?:\.\d+)?)\s*%\)\s*$/);
    let percent = null;
    if (percentMatch) {
      line = percentMatch[1].trim();
      percent = parseFloat(percentMatch[2]);
    }
    const starMatch = line.match(/^(.*?)\s*\*+\s*$/);
    let footnoted = false;
    if (starMatch && tokenRegex.test(starMatch[1].trim())) {
      line = starMatch[1].trim();
      footnoted = true;
    }
    if (line.startsWith('**') || /^when\b/i.test(line) || line.length > 40) {
      // Free-text footnote / explanatory sentence, not a substrate token.
      notes.push(line);
      return;
    }
    if (tokenRegex.test(line)) {
      tokens.push({ value: canonicalizeToken(line, tokenRegex), percent, footnoted, concentration });
      if (concentration && auditLog) {
        auditLog.push({
          field: fieldName, sourceRow, raw: original, normalized: canonicalizeToken(line, tokenRegex),
          rule: `leading concentration prefix "${concentration}" stripped and retained as metadata`,
        });
      }
      return;
    }
    // Trailing free-text after a valid leading token, e.g. "Mn2+ (62% of Mg2+)".
    const leadingMatch = line.match(/^(\S+)\s*(\(.*\))?\s*$/);
    if (leadingMatch && tokenRegex.test(leadingMatch[1])) {
      tokens.push({ value: canonicalizeToken(leadingMatch[1], tokenRegex), percent, footnoted, concentration });
      if (auditLog && leadingMatch[2]) {
        auditLog.push({
          field: fieldName, sourceRow, raw: original, normalized: canonicalizeToken(leadingMatch[1], tokenRegex),
          rule: `trailing annotation "${leadingMatch[2]}" retained as note, not parsed as a separate substrate`,
        });
      }
      return;
    }
    if (line) {
      notes.push(line);
      if (auditLog) {
        auditLog.push({
          field: fieldName,
          sourceRow,
          raw: line,
          rule: 'unrecognized token retained as free-text note (not counted as a substrate)',
        });
      }
    }
  });

  return { tokens, notes };
}

// ---------------------------------------------------------------------------
// Free-text list explosion (aromatic acceptor substrate names — newline only,
// since chemical names legitimately contain commas)
// ---------------------------------------------------------------------------
function explodeFreeTextList(raw) {
  if (!raw) return [];
  return String(raw)
    .split('\n')
    .map((l) => l.replace(/^\d+[.)]\s*/, '').trim())
    .filter(Boolean);
}

// ---------------------------------------------------------------------------
// Regio-position canonicalization. Extracts a short "C3" / "O5" style label
// from each free-text regio token so records can be filtered/grouped by
// position — while the raw tokens (and their tie to this record's own
// acceptorClass) are always kept alongside, so a position is never presented
// without its acceptor-class context and never merged across classes.
// ---------------------------------------------------------------------------
const REGIO_POSITION_REGEX = /^([CO])[\s-]?(\d+)?/i;

function canonicalizeRegioPositions(regioTokens) {
  const positions = [];
  for (const token of regioTokens) {
    const trimmed = token.trim();
    if (/^(n\.?a\.?|no precise annotation)$/i.test(trimmed)) continue;
    const m = trimmed.match(REGIO_POSITION_REGEX);
    if (m) {
      const canonical = m[1].toUpperCase() + (m[2] || '');
      if (!positions.includes(canonical)) positions.push(canonical);
    } else if (!positions.includes('Other')) {
      positions.push('Other');
    }
  }
  return positions;
}

// ---------------------------------------------------------------------------
// pH / temperature parsing with plausibility-based swap correction
// ---------------------------------------------------------------------------
function parseRangeField(raw, { min, max }) {
  if (!raw) return { low: null, high: null, mid: null, raw: raw || null, valid: null, note: null };
  const text = String(raw).trim();
  const rangeMatch = text.match(/(\d+(?:[.,]\d+)?)\s*(?:to|-|–|—)\s*(\d+(?:[.,]\d+)?)/);
  let low = null;
  let high = null;
  let note = null;

  if (rangeMatch && !/[A-Za-z]/.test(text.slice(rangeMatch.index, rangeMatch.index + rangeMatch[0].length + 3).replace(rangeMatch[0], ''))) {
    low = toNumber(rangeMatch[1]);
    high = toNumber(rangeMatch[2]);
  } else {
    const nums = standaloneNumbers(text);
    if (nums.length === 1) {
      low = high = nums[0];
    } else if (nums.length > 1) {
      low = high = nums[0];
      note = `Multiple numeric tokens found in "${text}"; used first (${nums[0]}) and flagged for manual review.`;
    }
  }

  if (low == null) {
    return { low: null, high: null, mid: null, raw: text, valid: false, note: `No parseable numeric value in "${text}".` };
  }

  const mid = (low + high) / 2;
  const valid = low >= min && low <= max && high >= min && high <= max;
  return { low, high, mid, raw: text, valid, note };
}

function parsePhAndTemp(phRaw, tempRaw) {
  const auditNotes = [];
  let ph = parseRangeField(phRaw, { min: PH_MIN, max: PH_MAX });
  let temp = parseRangeField(tempRaw, { min: TEMP_MIN, max: TEMP_MAX });
  let swapped = false;

  const phOutOfRange = phRaw && ph.low != null && (ph.low > PH_MAX || ph.high > PH_MAX);
  const tempLooksLikePh =
    tempRaw && temp.low != null && temp.low <= PH_MAX && temp.high <= PH_MAX;
  const phLooksLikeTemp =
    phRaw && ph.low != null && ph.low <= TEMP_MAX && ph.high <= TEMP_MAX;

  if (phOutOfRange && tempLooksLikePh && phLooksLikeTemp) {
    const newPh = parseRangeField(tempRaw, { min: PH_MIN, max: PH_MAX });
    const newTemp = parseRangeField(phRaw, { min: TEMP_MIN, max: TEMP_MAX });
    auditNotes.push({
      rule: 'pH/temperature plausibility swap',
      detail: `Raw pH "${phRaw}" is outside 0–14; raw temperature "${tempRaw}" is a plausible pH. Columns swapped back: pH ← "${tempRaw}", temperature ← "${phRaw}".`,
    });
    ph = newPh;
    temp = newTemp;
    swapped = true;
  }

  return { ph, temp, swapped, auditNotes };
}

// ---------------------------------------------------------------------------
// Km value parsing: "Label: number unit" per line
// ---------------------------------------------------------------------------
const KM_LINE_REGEX = /^(.*?):\s*([\d.]+)\s*(nM|µM|μM|uM|mM|M)\b/i;

function parseKmField(raw, acceptedDonorTokens) {
  if (!raw) return [];
  const donorNames = new Set(acceptedDonorTokens.map((t) => t.value.toUpperCase()));
  const lines = String(raw).split('\n').map((l) => l.trim()).filter(Boolean);
  const out = [];
  lines.forEach((line) => {
    const m = line.match(KM_LINE_REGEX);
    if (!m) return;
    const label = m[1].trim();
    const value = parseFloat(m[2]);
    let unitKey = m[3].toLowerCase();
    if (unitKey === 'um' || unitKey === 'μm') unitKey = 'µm';
    const factor = KM_UNIT_TO_UM[unitKey] ?? KM_UNIT_TO_UM[m[3]] ?? null;
    if (factor == null || Number.isNaN(value)) return;
    const isDonor = DONOR_TOKEN_REGEX.test(label) || donorNames.has(label.toUpperCase());
    out.push({
      label,
      rawValue: value,
      rawUnit: m[3],
      valueUM: value * factor,
      role: isDonor ? 'donor' : 'acceptor',
    });
  });
  return out;
}

// ---------------------------------------------------------------------------
// AhPT1 (S. No. 55) hardcoded cofactor-dependent special case. The source
// spreadsheet packs two distinct experimental conditions into one row using
// ragged parallel line-lists that cannot be safely auto-aligned across
// columns. Per the master prompt this is treated as a documented, manually
// curated override rather than an auto-parsed entry.
// ---------------------------------------------------------------------------
function ahpt1CofactorConditions(enzymeName) {
  if (enzymeName !== 'AhPT1') return null;
  return [
    {
      metal: 'Mg2+',
      acceptorSubstrate: 'Genistein',
      regio: 'C6',
      product: '6-prenylgenistein',
      outcome: 'active',
      note: 'Mg2+ supports 6-C-prenylation of genistein.',
    },
    {
      metal: 'Mn2+',
      acceptorSubstrate: "6-hydroxyflavone",
      regio: 'C5',
      product: '5-C-prenylated 6-hydroxyflavone',
      outcome: 'active-high-conversion',
      note: 'Mn2+ produces 5-C-prenylated 6-hydroxyflavone with high conversion.',
    },
    {
      metal: 'Mg2+',
      acceptorSubstrate: "6-hydroxyflavone",
      regio: null,
      product: null,
      outcome: 'undetectable',
      note: 'Activity toward 6-hydroxyflavone with Mg2+ was undetectable.',
    },
  ];
}

const PROMISCUITY_ACCEPTOR_THRESHOLD = 4;

function normalizeRow(row) {
  const auditLog = [];
  const manualReview = [];
  const sourceRow = row.__sourceRow;
  const sno = row['S. No.'];
  const enzymeRaw = row['Enzyme'] ? String(row['Enzyme']).trim() : null;
  const enzymeLines = enzymeRaw ? enzymeRaw.split('\n').map((l) => l.trim()).filter(Boolean) : [];
  const enzyme = enzymeLines[0] || null;
  const enzymeNote = enzymeLines.length > 1 ? enzymeLines.slice(1).join('; ') : null;
  if (enzymeNote) {
    manualReview.push({ sno, enzyme, sourceRow, reason: `Enzyme cell contains extra variant text beyond the primary name: "${enzymeNote}"` });
  }

  const originRaw = (row['Origin'] || '').toString().trim().toUpperCase();
  const origin = originRaw === 'P' ? 'Plant' : originRaw === 'F' ? 'Fungal' : null;
  if (!origin) manualReview.push({ sno, enzyme, sourceRow, reason: `Unrecognized Origin value "${row['Origin']}"` });

  const acceptorClass = normalizeAcceptorClass(row['Acceptor class'], auditLog);
  const family = row['Family'] ? String(row['Family']).trim() : null;
  const { genus, species, commonName, organism } = splitOrganism(row['Gene from organism']);

  const acceptedAcceptors = explodeFreeTextList(row['Prenyl acceptor (Aromatic substrate) - Accepted']);
  const mediumAcceptors = explodeFreeTextList(row['Prenyl acceptor (Aromatic substrate) - Medium to Not Accepted']);

  const acceptedDonors = explodeControlledList(
    row['Prenyl donor - Accepted'], DONOR_TOKEN_REGEX, 'Prenyl donor - Accepted', sourceRow, auditLog
  );
  const mediumDonors = explodeControlledList(
    row['Prenyl donor - Medium to Not Accepted'], DONOR_TOKEN_REGEX, 'Prenyl donor - Medium to Not Accepted', sourceRow, auditLog
  );
  const acceptedMetals = explodeControlledList(
    row['Metal ion - Accepted'], METAL_TOKEN_REGEX, 'Metal ion - Accepted', sourceRow, auditLog
  );
  const mediumMetals = explodeControlledList(
    row['Metal ion - Medium to Not Accepted'], METAL_TOKEN_REGEX, 'Metal ion - Medium to Not Accepted', sourceRow, auditLog
  );

  const primaryDonor = acceptedDonors.tokens[0]?.value || null;
  const allAcceptedDonors = acceptedDonors.tokens.map((t) => t.value);

  const { ph, temp, swapped, auditNotes } = parsePhAndTemp(row['Optimal pH'], row['Optimal temperature']);
  auditNotes.forEach((n) => auditLog.push({ field: 'Optimal pH / Optimal temperature', sourceRow, enzyme, ...n }));
  if (swapped) manualReview.push({ sno, enzyme, sourceRow, reason: 'pH/temperature columns auto-swapped (plausibility correction) — verify against source publication.' });

  const kmEntries = parseKmField(row['Km value'], acceptedDonors.tokens);

  const regioTokens = explodeFreeTextList(row['Regio specificity']);
  const regioPositions = canonicalizeRegioPositions(regioTokens);

  const allNotes = [...acceptedDonors.notes, ...mediumDonors.notes];
  const promiscuousDmapp =
    allAcceptedDonors.includes('DMAPP') &&
    (acceptedAcceptors.length >= PROMISCUITY_ACCEPTOR_THRESHOLD ||
      allNotes.some((n) => PROMISCUOUS_NOTE_REGEX.test(n)));
  if (promiscuousDmapp) {
    manualReview.push({
      sno,
      enzyme,
      sourceRow,
      reason: `Flagged as promiscuous DMAPP acceptor (heuristic: DMAPP accepted + ${acceptedAcceptors.length} accepted aromatic substrates, threshold ${PROMISCUITY_ACCEPTOR_THRESHOLD}). Confirm against source publication.`,
    });
  }

  const cofactorConditions = ahpt1CofactorConditions(enzyme);
  if (cofactorConditions) {
    manualReview.push({
      sno,
      enzyme,
      sourceRow,
      reason: 'AhPT1 cofactor-dependent activity (Mg2+ vs Mn2+) represented via a manually curated override — the source row packs both conditions into ragged parallel line-lists that cannot be auto-aligned. Verify against Yang et al. 2020.',
    });
  }

  if (kmEntries.length === 0 && row['Km value']) {
    // Free text present but nothing numerically extractable — expected for
    // most qualitative records; not flagged individually (see report summary).
  }

  const record = {
    id: sno,
    sourceRow,
    enzyme,
    enzymeNote,
    origin,
    originRaw: row['Origin'],
    acceptorClass: acceptorClass.value,
    acceptorClassRaw: row['Acceptor class'],
    family,
    organism,
    organismRaw: row['Gene from organism'],
    genus,
    species,
    commonName,
    expressionHost: row['Expression in'] ? String(row['Expression in']).trim() : null,
    product: row['Product'] || null,
    regioRaw: row['Regio specificity'] || null,
    regioTokens,
    regioPositions,
    year: row['Year'] != null ? Number(row['Year']) : null,
    author: row['Author'] || null,
    doi: row['doi'] || null,
    primaryDonor,
    allAcceptedDonors,
    mediumDonors: mediumDonors.tokens.map((t) => t.value),
    acceptedMetals: acceptedMetals.tokens.map((t) => t.value),
    mediumMetals: mediumMetals.tokens.map((t) => t.value),
    acceptedAcceptors,
    mediumAcceptors,
    kmEntries,
    ph,
    temp,
    phTempSwapped: swapped,
    promiscuousDmapp,
    cofactorConditions,
    dataCompleteness: computeCompleteness({ ph, temp, kmEntries, acceptedDonors: allAcceptedDonors, acceptedMetals: acceptedMetals.tokens }),
  };

  return { record, auditLog, manualReview };
}

function computeCompleteness(r) {
  let score = 0;
  let total = 4;
  if (r.ph.valid) score++;
  if (r.temp.valid) score++;
  if (r.kmEntries.length > 0) score++;
  if (r.acceptedDonors.length > 0) score++;
  if (score === total) return 'complete';
  if (score === 0) return 'minimal';
  return 'partial';
}

function normalizeDataset(rows) {
  const records = [];
  const auditLog = [];
  const manualReview = [];
  for (const row of rows) {
    const { record, auditLog: rowAudit, manualReview: rowReview } = normalizeRow(row);
    records.push(record);
    auditLog.push(...rowAudit);
    manualReview.push(...rowReview);
  }

  const knownSno = new Set(records.map((r) => r.id));
  [186, 187].forEach((n) => {
    if (!knownSno.has(n)) {
      manualReview.push({
        sno: n,
        enzyme: null,
        sourceRow: null,
        reason: `Referenced in the prior master prompt's special donor-rule list but no S. No. ${n} exists in the current ${records.length}-record workbook — likely a stale reference from an earlier dataset revision.`,
      });
    }
  });

  return { records, auditLog, manualReview };
}

/* ============ ported from ../webapp/server/ingest/validate.js ============ */
/**
 * Structural validation performed before any normalization. Returns
 * { ok, errors } — errors is non-empty when the file cannot be ingested.
 */
function validateWorkbook({ headers, rows }) {
  const errors = [];

  const normalizedHeaders = headers.map((h) => h.toLowerCase());
  const missing = REQUIRED_COLUMNS.filter(
    (col) => !normalizedHeaders.includes(col.toLowerCase())
  );
  if (missing.length > 0) {
    errors.push(`Missing required column(s): ${missing.join(', ')}`);
  }

  if (rows.length === 0) {
    errors.push('No data rows found (file has a header row but no records).');
  }

  const seenSno = new Set();
  let missingSno = 0;
  let missingEnzyme = 0;
  let missingOrigin = 0;
  rows.forEach((row) => {
    const sno = row['S. No.'];
    if (sno === null || sno === undefined || sno === '') missingSno++;
    else {
      if (seenSno.has(sno)) errors.push(`Duplicate S. No. value: ${sno} (row ${row.__sourceRow})`);
      seenSno.add(sno);
    }
    if (!row['Enzyme']) missingEnzyme++;
    const origin = (row['Origin'] || '').toString().trim().toUpperCase();
    if (origin !== 'P' && origin !== 'F') missingOrigin++;
  });

  if (missingSno > 0) errors.push(`${missingSno} row(s) missing "S. No."`);
  if (missingEnzyme > 0) errors.push(`${missingEnzyme} row(s) missing "Enzyme"`);
  if (missingOrigin > 0) {
    errors.push(
      `${missingOrigin} row(s) have an "Origin" value other than "P" or "F" (plant/fungal only).`
    );
  }

  return { ok: errors.length === 0, errors };
}

/* ============ ported from ../webapp/server/stats.js ============ */
// Minimal, dependency-free statistics: contingency tables, chi-square,
// Cramer's V, and a chi-square upper-tail p-value via the regularized
// incomplete gamma function (Numerical-Recipes-style series/continued
// fraction). Good to ~1e-10 relative error, ample for reporting p-values.

function logGamma(x) {
  const g = 7;
  const c = [
    0.99999999999980993, 676.5203681218851, -1259.1392167224028,
    771.32342877765313, -176.61502916214059, 12.507343278686905,
    -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7,
  ];
  if (x < 0.5) return Math.log(Math.PI / Math.sin(Math.PI * x)) - logGamma(1 - x);
  x -= 1;
  let a = c[0];
  const t = x + g + 0.5;
  for (let i = 1; i < g + 2; i++) a += c[i] / (x + i);
  return 0.5 * Math.log(2 * Math.PI) + (x + 0.5) * Math.log(t) - t + Math.log(a);
}

function lowerIncompleteGammaSeries(a, x) {
  let sum = 1 / a;
  let term = sum;
  for (let n = 1; n < 500; n++) {
    term *= x / (a + n);
    sum += term;
    if (Math.abs(term) < Math.abs(sum) * 1e-15) break;
  }
  return sum * Math.exp(-x + a * Math.log(x) - logGamma(a));
}

function upperIncompleteGammaCF(a, x) {
  let b = x + 1 - a;
  let c = 1e300;
  let d = 1 / b;
  let h = d;
  for (let i = 1; i < 500; i++) {
    const an = -i * (i - a);
    b += 2;
    d = an * d + b;
    if (Math.abs(d) < 1e-300) d = 1e-300;
    c = b + an / c;
    if (Math.abs(c) < 1e-300) c = 1e-300;
    d = 1 / d;
    const del = d * c;
    h *= del;
    if (Math.abs(del - 1) < 1e-15) break;
  }
  return Math.exp(-x + a * Math.log(x) - logGamma(a)) * h;
}

/** Regularized upper incomplete gamma Q(a, x) = 1 - P(a, x). */
function gammaQ(a, x) {
  if (x < 0 || a <= 0) return NaN;
  if (x === 0) return 1;
  if (x < a + 1) return 1 - lowerIncompleteGammaSeries(a, x);
  return upperIncompleteGammaCF(a, x);
}

/** Upper-tail p-value for a chi-square statistic with df degrees of freedom. */
function chiSquarePValue(chi2, df) {
  if (chi2 <= 0 || df <= 0) return 1;
  return Math.max(0, Math.min(1, gammaQ(df / 2, chi2 / 2)));
}

/** Builds a contingency table (rows x cols) of counts from records. */
function contingencyTable(records, rowField, colField) {
  const rowVals = [];
  const colVals = [];
  const rowIndex = new Map();
  const colIndex = new Map();
  const counts = [];

  for (const rec of records) {
    const rv = rowField(rec);
    const cv = colField(rec);
    if (rv == null || cv == null) continue;
    if (!rowIndex.has(rv)) {
      rowIndex.set(rv, rowVals.length);
      rowVals.push(rv);
      counts.push([]);
    }
    if (!colIndex.has(cv)) {
      colIndex.set(cv, colVals.length);
      colVals.push(cv);
    }
    const ri = rowIndex.get(rv);
    const ci = colIndex.get(cv);
    counts[ri][ci] = (counts[ri][ci] || 0) + 1;
  }
  for (const row of counts) {
    for (let c = 0; c < colVals.length; c++) row[c] = row[c] || 0;
  }
  return { rowVals, colVals, counts };
}

function chiSquareTest(table) {
  const { rowVals, colVals, counts } = table;
  const rowTotals = counts.map((row) => row.reduce((a, b) => a + b, 0));
  const colTotals = colVals.map((_, c) => counts.reduce((a, row) => a + row[c], 0));
  const n = rowTotals.reduce((a, b) => a + b, 0);
  if (n === 0 || rowVals.length < 2 || colVals.length < 2) {
    return { chi2: null, df: null, pValue: null, cramersV: null, n };
  }
  let chi2 = 0;
  for (let r = 0; r < rowVals.length; r++) {
    for (let c = 0; c < colVals.length; c++) {
      const expected = (rowTotals[r] * colTotals[c]) / n;
      if (expected > 0) chi2 += (counts[r][c] - expected) ** 2 / expected;
    }
  }
  const df = (rowVals.length - 1) * (colVals.length - 1);
  const pValue = chiSquarePValue(chi2, df);
  const minDim = Math.min(rowVals.length - 1, colVals.length - 1);
  const cramersV = minDim > 0 ? Math.sqrt(chi2 / (n * minDim)) : null;
  return { chi2, df, pValue, cramersV, n };
}

function pearsonCorrelation(pairs) {
  const clean = pairs.filter(([a, b]) => Number.isFinite(a) && Number.isFinite(b));
  const n = clean.length;
  if (n < 3) return { r: null, n };
  const meanX = clean.reduce((s, [a]) => s + a, 0) / n;
  const meanY = clean.reduce((s, [, b]) => s + b, 0) / n;
  let num = 0, denX = 0, denY = 0;
  for (const [a, b] of clean) {
    num += (a - meanX) * (b - meanY);
    denX += (a - meanX) ** 2;
    denY += (b - meanY) ** 2;
  }
  const r = denX > 0 && denY > 0 ? num / Math.sqrt(denX * denY) : null;
  return { r, n };
}

/* ============ ported from ../webapp/server/analysis.js ============ */
function toArrayParam(v) {
  if (v == null) return null;
  if (Array.isArray(v)) return v;
  return String(v).split(',').map((s) => s.trim()).filter(Boolean);
}

/**
 * Applies the sidebar filter set to the canonical record list.
 * filters: { kingdom, family, genus, species, acceptorClass, donor, donorRole,
 *   metal, regioPosition, host, yearFrom, yearTo, completeness, promiscuousDmapp,
 *   search, includeMissing }
 */
function applyFilters(records, filters = {}) {
  const kingdom = toArrayParam(filters.kingdom);
  const family = toArrayParam(filters.family);
  const genus = toArrayParam(filters.genus);
  const species = toArrayParam(filters.species);
  const acceptorClass = toArrayParam(filters.acceptorClass);
  const donor = toArrayParam(filters.donor);
  const metal = toArrayParam(filters.metal);
  const regioPosition = toArrayParam(filters.regioPosition);
  const host = toArrayParam(filters.host);
  const completeness = toArrayParam(filters.completeness);
  const donorRole = filters.donorRole || 'accepted'; // 'primary' | 'accepted'
  const includeMissing = filters.includeMissing !== 'false' && filters.includeMissing !== false;
  const yearFrom = filters.yearFrom ? Number(filters.yearFrom) : null;
  const yearTo = filters.yearTo ? Number(filters.yearTo) : null;
  const promiscuousDmapp = filters.promiscuousDmapp === 'true' || filters.promiscuousDmapp === true;
  const search = (filters.search || '').trim().toLowerCase();

  function passesSet(recValue, set, allowMissing) {
    if (!set || set.length === 0) return true;
    if (recValue == null) return allowMissing;
    return set.includes(recValue);
  }
  function passesSetMulti(recValues, set, allowMissing) {
    if (!set || set.length === 0) return true;
    if (!recValues || recValues.length === 0) return allowMissing;
    return recValues.some((v) => set.includes(v));
  }

  return records.filter((r) => {
    if (kingdom && kingdom.length && !kingdom.includes('All') && !kingdom.includes(r.origin)) return false;
    if (!passesSet(r.family, family, includeMissing)) return false;
    if (!passesSet(r.genus, genus, includeMissing)) return false;
    if (!passesSet(r.species, species, includeMissing)) return false;
    if (!passesSet(r.acceptorClass, acceptorClass, includeMissing)) return false;
    const donorValues = donorRole === 'primary' ? (r.primaryDonor ? [r.primaryDonor] : []) : r.allAcceptedDonors;
    if (!passesSetMulti(donorValues, donor, includeMissing)) return false;
    if (!passesSetMulti(r.acceptedMetals, metal, includeMissing)) return false;
    if (!passesSetMulti(r.regioPositions, regioPosition, includeMissing)) return false;
    if (!passesSet(r.expressionHost, host, includeMissing)) return false;
    if (!passesSet(r.dataCompleteness, completeness, includeMissing)) return false;
    if (promiscuousDmapp && !r.promiscuousDmapp) return false;
    if (yearFrom != null && (r.year == null || r.year < yearFrom)) return false;
    if (yearTo != null && (r.year == null || r.year > yearTo)) return false;

    if (search) {
      const haystack = [
        r.enzyme, r.organism, r.family, r.genus, r.species, r.acceptorClass,
        r.author, r.doi, r.product, ...(r.acceptedAcceptors || []), ...(r.allAcceptedDonors || []),
        r.organismRaw, r.acceptorClassRaw,
      ].filter(Boolean).join(' ').toLowerCase();
      if (!haystack.includes(search)) return false;
    }
    return true;
  });
}

function distinctSorted(values) {
  return [...new Set(values.filter((v) => v != null && v !== ''))].sort((a, b) =>
    String(a).localeCompare(String(b))
  );
}

/** Cascading filter option lists, computed from a record set already narrowed
 *  by every OTHER active filter (so options always reflect what's reachable). */
function filterOptions(records) {
  return {
    kingdom: ['Plant', 'Fungal'],
    family: distinctSorted(records.map((r) => r.family)),
    genus: distinctSorted(records.map((r) => r.genus)),
    species: distinctSorted(records.map((r) => r.species)),
    acceptorClass: distinctSorted(records.map((r) => r.acceptorClass)),
    donor: distinctSorted(records.flatMap((r) => r.allAcceptedDonors)),
    metal: distinctSorted(records.flatMap((r) => r.acceptedMetals)),
    regioPosition: distinctSorted(records.flatMap((r) => r.regioPositions)),
    host: distinctSorted(records.map((r) => r.expressionHost)),
    completeness: distinctSorted(records.map((r) => r.dataCompleteness)),
    yearMin: Math.min(...records.map((r) => r.year).filter(Number.isFinite)),
    yearMax: Math.max(...records.map((r) => r.year).filter(Number.isFinite)),
  };
}

function kpis(records) {
  const plant = records.filter((r) => r.origin === 'Plant');
  const fungal = records.filter((r) => r.origin === 'Fungal');
  const years = records.map((r) => r.year).filter(Number.isFinite);
  const families = distinctSorted(plant.map((r) => r.family));
  const genera = distinctSorted(plant.map((r) => r.genus));
  const acceptorClasses = distinctSorted(records.map((r) => r.acceptorClass));
  const withBothKm = records.filter(
    (r) => r.kmEntries.some((k) => k.role === 'donor') && r.kmEntries.some((k) => k.role === 'acceptor')
  ).length;
  return {
    total: records.length,
    plant: plant.length,
    fungal: fungal.length,
    plantFamilies: families.length,
    plantGenera: genera.length,
    acceptorClasses: acceptorClasses.length,
    yearMin: years.length ? Math.min(...years) : null,
    yearMax: years.length ? Math.max(...years) : null,
    enzymesWithFullKmPair: withBothKm,
  };
}

function topOf(counts) {
  const entries = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  return entries.length ? { value: entries[0][0], count: entries[0][1] } : null;
}

/** Fast-read highlights for the Overview tab: leaderboard-style top values,
 *  computed live from whatever record set is passed (no stored constants). */
function highlights(records) {
  const acceptorCounts = new Map();
  const familyCounts = new Map();
  const donorCounts = new Map();
  const metalCounts = new Map();
  let cPos = 0, oPos = 0;
  records.forEach((r) => {
    if (r.acceptorClass) acceptorCounts.set(r.acceptorClass, (acceptorCounts.get(r.acceptorClass) || 0) + 1);
    if (r.family) familyCounts.set(r.family, (familyCounts.get(r.family) || 0) + 1);
    new Set(r.allAcceptedDonors).forEach((d) => donorCounts.set(d, (donorCounts.get(d) || 0) + 1));
    new Set(r.acceptedMetals).forEach((m) => metalCounts.set(m, (metalCounts.get(m) || 0) + 1));
    if (r.regioPositions?.some((p) => p.startsWith('C'))) cPos++;
    else if (r.regioPositions?.some((p) => p.startsWith('O'))) oPos++;
  });
  const complete = records.filter((r) => r.dataCompleteness === 'complete').length;
  const promiscuousCount = records.filter((r) => r.promiscuousDmapp).length;
  const ahpt1 = records.find((r) => r.enzyme === 'AhPT1');

  return {
    topAcceptorClass: topOf(acceptorCounts),
    topFamily: topOf(familyCounts),
    topDonor: topOf(donorCounts),
    topMetal: topOf(metalCounts),
    cPrenylationCount: cPos,
    oPrenylationCount: oPos,
    completeRecords: complete,
    totalRecords: records.length,
    promiscuousDmappCount: promiscuousCount,
    hasAhpt1SpecialCase: !!ahpt1?.cofactorConditions,
  };
}

/** One of the 6 plant / 6 fungal bivariate analyses.
 *  groupBy: 'family' | 'genus'; dimension: 'enzymeCount' | 'acceptorClass' | 'donor' */
function bivariate(records, origin, groupBy, dimension) {
  const subset = records.filter((r) => r.origin === origin);
  const groupField = (r) => r[groupBy];

  if (dimension === 'enzymeCount') {
    const counts = new Map();
    subset.forEach((r) => {
      const g = groupField(r);
      if (g == null) return;
      counts.set(g, (counts.get(g) || 0) + 1);
    });
    const total = subset.length;
    const rows = [...counts.entries()]
      .map(([group, count]) => ({ group, count, percent: total ? (count / total) * 100 : 0 }))
      .sort((a, b) => b.count - a.count);
    return { groupBy, dimension, unit: 'records', denominator: total, rows };
  }

  const useEntities = dimension === 'donor';
  const rows = [];
  const denomByGroup = new Map();
  subset.forEach((r) => {
    const g = groupField(r);
    if (g == null) return;
    denomByGroup.set(g, (denomByGroup.get(g) || 0) + 1);
  });

  const cellCounts = new Map(); // key: group|value -> count
  subset.forEach((r) => {
    const g = groupField(r);
    if (g == null) return;
    const values = dimension === 'acceptorClass'
      ? (r.acceptorClass ? [r.acceptorClass] : [])
      : r.allAcceptedDonors;
    const seen = new Set();
    values.forEach((v) => {
      if (seen.has(v)) return; // count each enzyme once per (group,value) pair
      seen.add(v);
      const key = `${g}||${v}`;
      cellCounts.set(key, (cellCounts.get(key) || 0) + 1);
    });
  });

  for (const [key, count] of cellCounts.entries()) {
    const [group, value] = key.split('||');
    const denom = denomByGroup.get(group) || 0;
    rows.push({ group, value, count, denominator: denom, percent: denom ? (count / denom) * 100 : 0 });
  }
  rows.sort((a, b) => a.group.localeCompare(b.group) || b.count - a.count);
  return { groupBy, dimension, unit: useEntities ? 'parsed-entities' : 'records', rows };
}

const BIVARIATE_SPECS = [
  ['family', 'enzymeCount'], ['family', 'acceptorClass'], ['family', 'donor'],
  ['genus', 'enzymeCount'], ['genus', 'acceptorClass'], ['genus', 'donor'],
];

function allBivariate(records) {
  const out = { plant: {}, fungal: {} };
  for (const origin of ['Plant', 'Fungal']) {
    const key = origin.toLowerCase();
    for (const [groupBy, dimension] of BIVARIATE_SPECS) {
      out[key][`${groupBy}_${dimension}`] = bivariate(records, origin, groupBy, dimension);
    }
  }
  return out;
}

function statisticalAnalysis(records) {
  const kingdomAcceptor = chiSquareTest(
    contingencyTable(records, (r) => r.origin, (r) => r.acceptorClass)
  );
  const kingdomDonor = chiSquareTest(
    contingencyTable(
      records.flatMap((r) => r.allAcceptedDonors.map((d) => ({ origin: r.origin, donor: d }))),
      (r) => r.origin, (r) => r.donor
    )
  );
  const kmPairs = records
    .map((r) => {
      const donorKm = r.kmEntries.find((k) => k.role === 'donor');
      const acceptorKm = r.kmEntries.find((k) => k.role === 'acceptor');
      return donorKm && acceptorKm ? [Math.log10(donorKm.valueUM), Math.log10(acceptorKm.valueUM)] : null;
    })
    .filter(Boolean);
  const kmCorrelation = pearsonCorrelation(kmPairs);

  const phByOrigin = { Plant: [], Fungal: [] };
  const tempByOrigin = { Plant: [], Fungal: [] };
  records.forEach((r) => {
    if (r.ph.valid && r.ph.mid != null) phByOrigin[r.origin]?.push(r.ph.mid);
    if (r.temp.valid && r.temp.mid != null) tempByOrigin[r.origin]?.push(r.temp.mid);
  });

  const missingness = {
    donorKm: records.filter((r) => !r.kmEntries.some((k) => k.role === 'donor')).length,
    acceptorKm: records.filter((r) => !r.kmEntries.some((k) => k.role === 'acceptor')).length,
    ph: records.filter((r) => !r.ph.valid).length,
    temperature: records.filter((r) => !r.temp.valid).length,
    total: records.length,
  };

  return {
    kingdomVsAcceptorClass: { ...kingdomAcceptor, label: "Kingdom × Acceptor class (χ², Cramér's V)" },
    kingdomVsDonor: { ...kingdomDonor, label: "Kingdom × Prenyl donor, parsed-entity level (χ², Cramér's V)" },
    donorAcceptorKmCorrelation: { ...kmCorrelation, label: 'log10(Donor Km) vs log10(Acceptor Km), Pearson r' },
    phByOrigin: summarizeNumeric(phByOrigin),
    tempByOrigin: summarizeNumeric(tempByOrigin),
    missingness,
  };
}

function summarizeNumeric(byOrigin) {
  const out = {};
  for (const [origin, values] of Object.entries(byOrigin)) {
    if (values.length === 0) { out[origin] = { n: 0 }; continue; }
    const sorted = [...values].sort((a, b) => a - b);
    const mean = values.reduce((a, b) => a + b, 0) / values.length;
    out[origin] = {
      n: values.length,
      mean: round2(mean),
      median: round2(sorted[Math.floor(sorted.length / 2)]),
      min: round2(sorted[0]),
      max: round2(sorted[sorted.length - 1]),
    };
  }
  return out;
}
function round2(n) { return Math.round(n * 100) / 100; }

/** Data-grounded observations, explicitly labeled as computed (not claims). */
function biologicalInsights(records) {
  const stats = statisticalAnalysis(records);
  const insights = [];

  if (stats.kingdomVsAcceptorClass.pValue != null) {
    const s = stats.kingdomVsAcceptorClass;
    insights.push({
      kingdom: 'both',
      text: `Computed observation: kingdom (plant vs. fungal) and acceptor class are associated in this dataset (χ²=${round2(s.chi2)}, df=${s.df}, p=${s.pValue < 0.0001 ? '<0.0001' : round2(s.pValue)}, Cramér's V=${round2(s.cramersV)}, n=${s.n}).`,
    });
  }

  const donorByOrigin = { Plant: new Map(), Fungal: new Map() };
  records.forEach((r) => r.allAcceptedDonors.forEach((d) => {
    const m = donorByOrigin[r.origin];
    if (m) m.set(d, (m.get(d) || 0) + 1);
  }));
  for (const origin of ['Plant', 'Fungal']) {
    const entries = [...donorByOrigin[origin].entries()].sort((a, b) => b[1] - a[1]);
    if (entries.length) {
      insights.push({
        kingdom: origin.toLowerCase(),
        text: `Computed observation: the most frequently accepted prenyl donor among ${origin.toLowerCase()} records is ${entries[0][0]} (${entries[0][1]} of ${records.filter((r) => r.origin === origin).length} ${origin.toLowerCase()} records).`,
      });
    }
  }

  const promiscuous = records.filter((r) => r.promiscuousDmapp);
  if (promiscuous.length) {
    insights.push({
      kingdom: 'both',
      text: `Computed observation: ${promiscuous.length} record(s) are heuristically flagged as promiscuous DMAPP acceptors (DMAPP accepted + ≥4 distinct accepted aromatic substrates): ${promiscuous.map((r) => r.enzyme).join(', ')}. Flag is a deterministic rule over existing fields, not a literature claim — see manual-review list.`,
    });
  }

  return insights;
}

/** Acceptor class × Regio position — the two axes are always kept together
 *  so a regio position is never presented without which acceptor class it
 *  belongs to (Flavonoid C3 and Coumarin C3 stay distinct cells, never
 *  summed into one "C3" total). */
function regioByAcceptorClass(records) {
  const cellCounts = new Map(); // "acceptorClass||position" -> count
  const classDenominator = new Map();
  records.forEach((r) => {
    if (!r.acceptorClass || !r.regioPositions.length) return;
    classDenominator.set(r.acceptorClass, (classDenominator.get(r.acceptorClass) || 0) + 1);
    const seen = new Set();
    r.regioPositions.forEach((pos) => {
      if (seen.has(pos)) return;
      seen.add(pos);
      const key = `${r.acceptorClass}||${pos}`;
      cellCounts.set(key, (cellCounts.get(key) || 0) + 1);
    });
  });
  const rows = [];
  for (const [key, count] of cellCounts.entries()) {
    const [acceptorClass, regioPosition] = key.split('||');
    const denom = classDenominator.get(acceptorClass) || 0;
    rows.push({ acceptorClass, regioPosition, count, denominator: denom, percent: denom ? (count / denom) * 100 : 0 });
  }
  rows.sort((a, b) => a.acceptorClass.localeCompare(b.acceptorClass) || b.count - a.count);
  return { unit: 'records (record counted once per distinct position within its own acceptor class)', rows };
}

function literature(records) {
  const byYear = new Map();
  records.forEach((r) => {
    if (r.year == null) return;
    byYear.set(r.year, (byYear.get(r.year) || 0) + 1);
  });
  const trend = [...byYear.entries()].sort((a, b) => a[0] - b[0]).map(([year, count]) => ({ year, count }));
  const items = records.map((r) => ({
    id: r.id, enzyme: r.enzyme, author: r.author, year: r.year, doi: r.doi, origin: r.origin,
  }));
  return { trend, items };
}

/* ============ ported from ../webapp/server/search.js ============ */
// Free, 100%-local smart search over the dataset — keyword retrieval with a
// deterministic (non-AI) summary. No external API, no cost, no API key.

const STOPWORDS = new Set(['the', 'a', 'an', 'is', 'are', 'was', 'were', 'of', 'in', 'on', 'for', 'to', 'and', 'or',
  'which', 'what', 'how', 'many', 'does', 'do', 'with', 'that', 'this', 'has', 'have', 'any', 'all', 'me', 'about']);

// Common Arabic domain terms mapped to the English tokens actually stored in
// the dataset. The underlying records are all in English (enzyme names,
// families, chemical names), so an Arabic query can only ever match via this
// bridge — it is intentionally small and scoped to terms that appear in this
// dataset, not a general translator.
const ARABIC_TERM_MAP = {
  'فطري': 'fungal', 'فطر': 'fungal', 'فطريات': 'fungal',
  'نباتي': 'plant', 'نبات': 'plant', 'نباتات': 'plant',
  'انزيم': 'enzyme', 'إنزيم': 'enzyme', 'انزيمات': 'enzyme', 'إنزيمات': 'enzyme',
  'حرارة': 'temperature', 'الحرارة': 'temperature', 'درجة': 'temperature',
  'حموضة': 'ph', 'الحموضة': 'ph',
  'معدن': 'metal', 'المعدن': 'metal', 'معادن': 'metal', 'كوفاكتور': 'cofactor',
  'دونور': 'donor', 'مانح': 'donor', 'مانحات': 'donor',
  'مستقبل': 'acceptor', 'مستقبلات': 'acceptor',
  'عائلة': 'family', 'الفصيلة': 'family', 'فصيلة': 'family',
  'جنس': 'genus',
  'سنة': 'year', 'عام': 'year',
  'مؤلف': 'author', 'كاتب': 'author',
  'خميرة': 'yeast',
};

// Matches Latin letters/digits AND Arabic-script letters (Unicode block
// U+0600–U+06FF), so an Arabic query produces real tokens instead of an
// empty list.
const TOKEN_REGEX = /[a-z0-9'+-]+|[؀-ۿ]+/g;

function tokenize(text) {
  const raw = String(text).toLowerCase().match(TOKEN_REGEX) || [];
  return raw.map((t) => ARABIC_TERM_MAP[t] || t);
}

function recordSearchableText(r) {
  return [
    r.enzyme, r.organism, r.family, r.genus, r.species, r.acceptorClass,
    r.primaryDonor, ...(r.allAcceptedDonors || []), ...(r.acceptedMetals || []),
    ...(r.acceptedAcceptors || []), r.expressionHost, r.author, r.doi, r.origin,
    r.year, r.product, r.ph?.valid ? `ph ${r.ph.mid}` : '', r.temp?.valid ? `temperature ${r.temp.mid}` : '',
    ...(r.regioTokens || []),
  ].filter(Boolean).join(' ').toLowerCase();
}

/** Keyword retrieval: score every record by query-term overlap, return the top N.
 *  Returns an empty match list (never a misleading arbitrary fallback) when
 *  the query has real terms but none of them actually appear in any record. */
function retrieveRelevantRecords(question, records, topN = 20) {
  const allTerms = tokenize(question);
  const terms = allTerms.filter((t) => !STOPWORDS.has(t) && t.length > 1);

  if (terms.length === 0) {
    return { matches: [], terms: [], noUsableTerms: true };
  }

  const scored = records.map((r) => {
    const text = recordSearchableText(r);
    let score = 0;
    for (const term of terms) {
      if (text.includes(term)) score += 1;
      if (r.enzyme && r.enzyme.toLowerCase() === term) score += 3;
    }
    return { r, score };
  });

  scored.sort((a, b) => b.score - a.score);
  const withHits = scored.filter((s) => s.score > 0);
  return { matches: withHits.slice(0, topN).map((s) => s.r), terms, noUsableTerms: false };
}

function mostCommon(values) {
  const counts = new Map();
  values.forEach((v) => { if (v) counts.set(v, (counts.get(v) || 0) + 1); });
  let best = null, bestCount = 0;
  for (const [v, c] of counts.entries()) if (c > bestCount) { best = v; bestCount = c; }
  return best ? { value: best, count: bestCount } : null;
}

/** A short, deterministic (rule-based, not AI-generated) summary of the matches. */
function summarize(matches, totalCount, terms, noUsableTerms) {
  if (noUsableTerms) {
    return 'Could not extract any searchable keyword from that query — try a specific enzyme name, family, genus, acceptor class, donor, or metal ion.';
  }
  if (matches.length === 0) {
    return `No records matched "${terms.join(', ')}" in the current filtered set. Try a different spelling or a broader term (e.g. an acceptor class or family name instead of a full sentence).`;
  }
  const plant = matches.filter((r) => r.origin === 'Plant').length;
  const fungal = matches.filter((r) => r.origin === 'Fungal').length;
  const topClass = mostCommon(matches.map((r) => r.acceptorClass));
  const topDonor = mostCommon(matches.flatMap((r) => r.allAcceptedDonors));

  const bits = [`${matches.length} of ${totalCount} records match`];
  bits.push(`${plant} plant, ${fungal} fungal`);
  if (topClass) bits.push(`most common acceptor class: ${topClass.value} (${topClass.count})`);
  if (topDonor) bits.push(`most common donor: ${topDonor.value} (${topDonor.count})`);
  return bits.join(' — ');
}

function searchRecords(question, records, topN = 20) {
  const { matches, terms, noUsableTerms } = retrieveRelevantRecords(question, records, topN);
  return {
    ok: true,
    summary: summarize(matches, records.length, terms, noUsableTerms),
    matchedTerms: terms,
    totalCount: records.length,
    matchCount: matches.length,
    records: matches.map((r) => ({
      id: r.id, enzyme: r.enzyme, origin: r.origin, family: r.family, genus: r.genus,
      acceptorClass: r.acceptorClass, primaryDonor: r.primaryDonor,
      allAcceptedDonors: r.allAcceptedDonors, acceptedMetals: r.acceptedMetals,
      expressionHost: r.expressionHost, year: r.year, author: r.author, doi: r.doi,
    })),
  };
}
